# Site settings
title: Joseph Kelly | Blog
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts and Projects of Joseph Kelly
url: "https://dirt19.github.io" # the base hostname & protocol for your site, e.g. http://example.com
email: joseph.p.kelly@ieee.org
domain: dirt19.github.io
#author:
#  name: "Joseph Kelly"
#  email: {{ site.email }}
#  url: {{ site.url }}

linkedin_username: josepkelly
github_username:  dirt19

# Build settings
baseurl: "" # the subpath of your site, e.g. /blog
#markdown: kramdown
#source: .
#destination: ./_site
#permalink: /:title
#paginate: 8
#paginate_path: /page:num/


#theme: minima #jekyll-theme-cayman, slate, long haul
theme: jekyll-theme-cayman
#remote_theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
